apiVersion: batch/v1
kind: Job
metadata:
  name: run-pred-perf-{tflower}-task{task}-fold{foldnum}{finetune}
spec:
  template:
    spec:
      containers:
      - name: run-pred-perf-{tflower}-task{task}-fold{foldnum}{finetune}
        image: kundajelab/genome-keras-sacred:gcp
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 7
            memory: 45Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 7
            memory: 45Gi
            nvidia.com/gpu: 1
        command:
        - /bin/bash
        - -c
        args:
        - gsutil cp gs://gbsc-gcp-lab-kundaje-user-amtseng/run_pred_perf.py ~;
          cd ~;
          python run_pred_perf.py -m {modelpath} -f /users/amtseng/tfmodisco/data/processed/ENCODE/config/{tf}/{tf}_training_paths.json -n {numtasks} -o {outpath} {taskarg};
      restartPolicy: Never
  backoffLimit: 0
